/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Agent */
        post: operations["create_agent_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approve-fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Fix */
        post: operations["approve_fix_v1_runs__run_id__approve_fix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Diff */
        post: operations["create_diff_v1_diffs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diffs/{diff_id}/request-pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Diff Pr */
        post: operations["request_diff_pr_v1_diffs__diff_id__request_pr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed-agent/tool-routing-smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Managed Agent Tool Routing Smoke */
        post: operations["managed_agent_tool_routing_smoke_v1_managed_agent_tool_routing_smoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentSpec */
        AgentSpec: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Systemprompt */
            systemPrompt: string;
            /** Tools */
            tools?: string[];
            sandboxPolicy?: components["schemas"]["SandboxPolicy"];
            /**
             * Managed
             * @default true
             */
            managed: boolean;
        };
        /** ApproveFixRequest */
        ApproveFixRequest: {
            /** Accepteddiffids */
            acceptedDiffIds: string[];
            /**
             * Applytoagent
             * @default true
             */
            applyToAgent: boolean;
        };
        /** ApproveFixResponse */
        ApproveFixResponse: {
            /** Applied */
            applied: boolean;
            agent: components["schemas"]["AgentSpec"];
            /** Message */
            message: string;
        };
        /**
         * CostTier
         * @enum {string}
         */
        CostTier: "low" | "medium" | "high" | "local";
        /** DiffCreate */
        DiffCreate: {
            /** Prompt */
            prompt: string;
            /** Targetpath */
            targetPath?: string | null;
            /**
             * Usemanagedagent
             * @default true
             */
            useManagedAgent: boolean;
            /** Allowedtools */
            allowedTools?: string[] | null;
        };
        /**
         * DiffProviderMode
         * @enum {string}
         */
        DiffProviderMode: "managed_agent" | "simulator";
        /** DiffResult */
        DiffResult: {
            /** Id */
            id: string;
            providerMode: components["schemas"]["DiffProviderMode"];
            status: components["schemas"]["DiffStatus"];
            /** Promptbefore */
            promptBefore: string;
            /** Promptafter */
            promptAfter: string;
            /** Unifieddiff */
            unifiedDiff: string;
            /** Interactionid */
            interactionId?: string | null;
            /** Environmentid */
            environmentId?: string | null;
            toolRoute: components["schemas"]["ToolRoute"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /** Targetpath */
            targetPath?: string | null;
            /** Prurl */
            prUrl?: string | null;
        };
        /**
         * DiffStatus
         * @enum {string}
         */
        DiffStatus: "ready" | "pr_requested" | "pr_created" | "failed";
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Scenarioid */
            scenarioId: string;
            severity: components["schemas"]["Severity"];
            /** Violatedpolicy */
            violatedPolicy: string;
            /** Evidence */
            evidence: string;
            /** Recommendation */
            recommendation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** ModelConfig */
        ModelConfig: {
            provider: components["schemas"]["ProviderKind"];
            /** Modelid */
            modelId: string;
            /** Displayname */
            displayName: string;
            /** Enabled */
            enabled: boolean;
            /** Unavailablereason */
            unavailableReason?: string | null;
            /** Capabilities */
            capabilities: string[];
            /** Privacynote */
            privacyNote: string;
            costTier: components["schemas"]["CostTier"];
            riskProfile: components["schemas"]["RiskProfile"];
            /** Supportstools */
            supportsTools: boolean;
        };
        /** PolicyDiff */
        PolicyDiff: {
            /** Id */
            id: string;
            /**
             * Target
             * @enum {string}
             */
            target: "system_prompt" | "sandbox_policy";
            /** Before */
            before: string;
            /** After */
            after: string;
            /** Rationale */
            rationale: string;
        };
        /**
         * ProviderKind
         * @enum {string}
         */
        ProviderKind: "google" | "openai" | "anthropic" | "local";
        /** Report */
        Report: {
            /** Runid */
            runId: string;
            /** Score */
            score: number;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Tracesummary */
            traceSummary: string;
            promptDiff: components["schemas"]["PolicyDiff"];
            toolPolicyDiff: components["schemas"]["PolicyDiff"];
            /** Regressiontests */
            regressionTests: string[];
        };
        /** RequestPrResponse */
        RequestPrResponse: {
            /** Id */
            id: string;
            providerMode: components["schemas"]["DiffProviderMode"];
            status: components["schemas"]["DiffStatus"];
            /** Promptbefore */
            promptBefore: string;
            /** Promptafter */
            promptAfter: string;
            /** Unifieddiff */
            unifiedDiff: string;
            /** Interactionid */
            interactionId?: string | null;
            /** Environmentid */
            environmentId?: string | null;
            toolRoute: components["schemas"]["ToolRoute"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /** Targetpath */
            targetPath?: string | null;
            /** Prurl */
            prUrl?: string | null;
            /** Branch */
            branch?: string | null;
            /** Commitsha */
            commitSha?: string | null;
        };
        /**
         * RiskProfile
         * @enum {string}
         */
        RiskProfile: "cloud" | "local";
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Agentid */
            agentId: string;
            /** Modelid */
            modelId: string;
            /** Scenarioids */
            scenarioIds: string[];
            /** @default queued */
            status: components["schemas"]["RunStatus"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /** Completedat */
            completedAt?: string | null;
            /** Score */
            score?: number | null;
        };
        /** RunCreate */
        RunCreate: {
            /** Agentid */
            agentId: string;
            /** Modelid */
            modelId: string;
            /** Scenarioids */
            scenarioIds: string[];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed";
        /** SandboxPolicy */
        SandboxPolicy: {
            /** Allowedtools */
            allowedTools?: string[];
            /** Alloweddomains */
            allowedDomains?: string[];
            /**
             * Filesystemscope
             * @default /workspace/agent
             */
            filesystemScope: string;
            /**
             * Networkegress
             * @default allowlist
             * @constant
             */
            networkEgress: "allowlist";
            /** Honeytokens */
            honeytokens?: string[];
        };
        /** Scenario */
        Scenario: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            category: components["schemas"]["ScenarioCategory"];
            /** Setupfixture */
            setupFixture: string;
            /** Attackgoal */
            attackGoal: string;
            /** Successcriteria */
            successCriteria: string;
            /** Expecteddefense */
            expectedDefense: string;
            defaultSeverity: components["schemas"]["Severity"];
        };
        /**
         * ScenarioCategory
         * @enum {string}
         */
        ScenarioCategory: "prompt_injection" | "rag_injection" | "secret_exfiltration" | "tool_misuse" | "unsafe_browsing" | "policy_bypass";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /** ToolRoute */
        ToolRoute: {
            /** Requestedtools */
            requestedTools: string[];
            /** Observedtools */
            observedTools: string[];
            /** Violations */
            violations: string[];
            /**
             * Rawstepcount
             * @default 0
             */
            rawStepCount: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfig"][];
                };
            };
        };
    };
    list_scenarios_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"][];
                };
            };
        };
    };
    create_agent_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_fix_v1_runs__run_id__approve_fix_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveFixRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveFixResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_diff_v1_diffs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_diff_pr_v1_diffs__diff_id__request_pr_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPrResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    managed_agent_tool_routing_smoke_v1_managed_agent_tool_routing_smoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
