/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/target-agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Target Agents */
        get: operations["list_target_agents_v1_target_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_v1_repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/github/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Github Agent */
        post: operations["import_github_agent_v1_github_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/target-agents/{target_agent_id}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Target Agent */
        post: operations["register_target_agent_v1_target_agents__target_agent_id__register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Agent */
        post: operations["create_agent_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent-projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Agent Project Endpoint */
        post: operations["import_agent_project_endpoint_v1_agent_projects_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Events Token */
        get: operations["get_run_events_token_v1_runs__run_id__events_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approve-fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Fix */
        post: operations["approve_fix_v1_runs__run_id__approve_fix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/request-pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Run Pr */
        post: operations["request_run_pr_v1_runs__run_id__request_pr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approve-pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Run Pr */
        post: operations["approve_run_pr_v1_runs__run_id__approve_pr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Diff */
        post: operations["create_diff_v1_diffs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diffs/{diff_id}/request-pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Diff Pr */
        post: operations["request_diff_pr_v1_diffs__diff_id__request_pr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed-agent/tool-routing-smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Managed Agent Tool Routing Smoke */
        post: operations["managed_agent_tool_routing_smoke_v1_managed_agent_tool_routing_smoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentImportRecord */
        AgentImportRecord: {
            /** Id */
            id: string;
            source: components["schemas"]["GitHubImportSource"];
            repository: components["schemas"]["RepositoryRecord"];
            agent: components["schemas"]["AgentSpec"];
            /** Warnings */
            warnings?: string[];
            /** Recommendedscenarioids */
            recommendedScenarioIds?: string[];
            /** Commitsha */
            commitSha?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
        };
        /** AgentProjectImportResponse */
        AgentProjectImportResponse: {
            agent: components["schemas"]["AgentSpec"];
            /** Warnings */
            warnings?: string[];
            /** Recommendedscenarioids */
            recommendedScenarioIds?: string[];
        };
        /** AgentSpec */
        AgentSpec: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Systemprompt */
            systemPrompt: string;
            /** Promptpath */
            promptPath?: string | null;
            /** Tools */
            tools?: string[];
            sandboxPolicy?: components["schemas"]["SandboxPolicy"];
            /**
             * Managed
             * @default true
             */
            managed: boolean;
            runtime?: components["schemas"]["TargetAgentRuntime"] | null;
        };
        /** ApproveFixRequest */
        ApproveFixRequest: {
            /** Accepteddiffids */
            acceptedDiffIds: string[];
            /**
             * Applytoagent
             * @default true
             */
            applyToAgent: boolean;
        };
        /** ApproveFixResponse */
        ApproveFixResponse: {
            /** Applied */
            applied: boolean;
            agent: components["schemas"]["AgentSpec"];
            /** Message */
            message: string;
        };
        /** Body_import_agent_project_endpoint_v1_agent_projects_import_post */
        Body_import_agent_project_endpoint_v1_agent_projects_import_post: {
            /**
             * Manifest
             * Format: binary
             */
            manifest: string;
            /** Promptfile */
            promptFile?: string | null;
        };
        /**
         * ComplianceFramework
         * @enum {string}
         */
        ComplianceFramework: "nist_ai_rmf" | "iso_iec_42001" | "owasp_llm_top_10";
        /** ComplianceMapping */
        ComplianceMapping: {
            framework: components["schemas"]["ComplianceFramework"];
            /** Control */
            control: string;
            /** Findingid */
            findingId?: string | null;
            status: components["schemas"]["ComplianceStatus"];
            /** Evidence */
            evidence: string;
        };
        /**
         * ComplianceStatus
         * @enum {string}
         */
        ComplianceStatus: "covered" | "gap" | "not_applicable";
        /**
         * CostTier
         * @enum {string}
         */
        CostTier: "low" | "medium" | "high" | "local";
        /** DiffCreate */
        DiffCreate: {
            /** Prompt */
            prompt: string;
            /** Targetpath */
            targetPath?: string | null;
            /**
             * Usemanagedagent
             * @default true
             */
            useManagedAgent: boolean;
            /** Allowedtools */
            allowedTools?: string[] | null;
        };
        /**
         * DiffProviderMode
         * @enum {string}
         */
        DiffProviderMode: "managed_agent" | "simulator";
        /** DiffResult */
        DiffResult: {
            /** Id */
            id: string;
            providerMode: components["schemas"]["DiffProviderMode"];
            status: components["schemas"]["DiffStatus"];
            /** Promptbefore */
            promptBefore: string;
            /** Promptafter */
            promptAfter: string;
            /** Unifieddiff */
            unifiedDiff: string;
            /** Interactionid */
            interactionId?: string | null;
            /** Environmentid */
            environmentId?: string | null;
            toolRoute: components["schemas"]["ToolRoute"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /** Targetpath */
            targetPath?: string | null;
            /** Prurl */
            prUrl?: string | null;
        };
        /**
         * DiffStatus
         * @enum {string}
         */
        DiffStatus: "ready" | "pr_requested" | "pr_created" | "failed";
        /** EventsTokenResponse */
        EventsTokenResponse: {
            /** Runid */
            runId: string;
            /** Token */
            token: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Scenarioid */
            scenarioId: string;
            severity: components["schemas"]["Severity"];
            /** Violatedpolicy */
            violatedPolicy: string;
            /** Evidence */
            evidence: string;
            /** Recommendation */
            recommendation: string;
        };
        /** GitHubImportSource */
        GitHubImportSource: {
            /** Owner */
            owner: string;
            /** Repo */
            repo: string;
            /** Ref */
            ref?: string | null;
            /**
             * Promptpath
             * @default .agents/AGENTS.md
             */
            promptPath: string;
            /**
             * Manifestpath
             * @default .devbox/agent.json
             */
            manifestPath: string | null;
            /** Installationid */
            installationId?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** ModelConfig */
        ModelConfig: {
            provider: components["schemas"]["ProviderKind"];
            /** Modelid */
            modelId: string;
            /** Displayname */
            displayName: string;
            /** Enabled */
            enabled: boolean;
            /** Unavailablereason */
            unavailableReason?: string | null;
            /** Capabilities */
            capabilities: string[];
            /** Privacynote */
            privacyNote: string;
            costTier: components["schemas"]["CostTier"];
            riskProfile: components["schemas"]["RiskProfile"];
            /** Supportstools */
            supportsTools: boolean;
        };
        /** PolicyDiff */
        PolicyDiff: {
            /** Id */
            id: string;
            /**
             * Target
             * @enum {string}
             */
            target: "system_prompt" | "sandbox_policy";
            /** Before */
            before: string;
            /** After */
            after: string;
            /** Rationale */
            rationale: string;
        };
        /**
         * ProviderKind
         * @enum {string}
         */
        ProviderKind: "google" | "openai" | "anthropic" | "local";
        /** Report */
        Report: {
            /** Runid */
            runId: string;
            /** Score */
            score: number;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Tracesummary */
            traceSummary: string;
            promptDiff: components["schemas"]["PolicyDiff"];
            toolPolicyDiff: components["schemas"]["PolicyDiff"];
            /** Regressiontests */
            regressionTests: string[];
            /** Riskroutes */
            riskRoutes?: components["schemas"]["RiskRoute"][];
            /** Scannerresults */
            scannerResults?: components["schemas"]["ScannerResult"][];
            /** Compliancemappings */
            complianceMappings?: components["schemas"]["ComplianceMapping"][];
            /** Cactusroute */
            cactusRoute?: string | null;
            /** Cactusreason */
            cactusReason?: string | null;
            /** Cactuslocalaudit */
            cactusLocalAudit?: string | null;
            /** Cactuscompliance */
            cactusCompliance?: string | null;
        };
        /** RepositoryRecord */
        RepositoryRecord: {
            /** Id */
            id: string;
            /** Installationid */
            installationId?: number | null;
            /** Owner */
            owner: string;
            /** Repo */
            repo: string;
            /** Fullname */
            fullName: string;
            /** Defaultbranch */
            defaultBranch?: string | null;
            /** Selectedref */
            selectedRef?: string | null;
            /** Htmlurl */
            htmlUrl?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
        };
        /** RequestPrResponse */
        RequestPrResponse: {
            /** Id */
            id: string;
            providerMode: components["schemas"]["DiffProviderMode"];
            status: components["schemas"]["DiffStatus"];
            /** Promptbefore */
            promptBefore: string;
            /** Promptafter */
            promptAfter: string;
            /** Unifieddiff */
            unifiedDiff: string;
            /** Interactionid */
            interactionId?: string | null;
            /** Environmentid */
            environmentId?: string | null;
            toolRoute: components["schemas"]["ToolRoute"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /** Targetpath */
            targetPath?: string | null;
            /** Prurl */
            prUrl?: string | null;
            /** Branch */
            branch?: string | null;
            /** Commitsha */
            commitSha?: string | null;
        };
        /**
         * RiskLane
         * @enum {string}
         */
        RiskLane: "local" | "cloud" | "scanner" | "sandbox";
        /**
         * RiskProfile
         * @enum {string}
         */
        RiskProfile: "cloud" | "local";
        /** RiskRoute */
        RiskRoute: {
            lane: components["schemas"]["RiskLane"];
            severity: components["schemas"]["Severity"];
            /** Rationale */
            rationale: string;
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Agentid */
            agentId: string;
            /** Modelid */
            modelId: string;
            /** Scenarioids */
            scenarioIds: string[];
            /**
             * Allowcloudanalysis
             * @default false
             */
            allowCloudAnalysis: boolean;
            /** @default queued */
            status: components["schemas"]["RunStatus"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /** Completedat */
            completedAt?: string | null;
            /** Score */
            score?: number | null;
        };
        /** RunCreate */
        RunCreate: {
            /** Agentid */
            agentId: string;
            /** Modelid */
            modelId: string;
            /** Scenarioids */
            scenarioIds: string[];
            /**
             * Allowcloudanalysis
             * @default false
             */
            allowCloudAnalysis: boolean;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed";
        /** SandboxPolicy */
        SandboxPolicy: {
            /** Allowedtools */
            allowedTools?: string[];
            /** Alloweddomains */
            allowedDomains?: string[];
            /**
             * Filesystemscope
             * @default /workspace/agent
             */
            filesystemScope: string;
            /**
             * Networkegress
             * @default allowlist
             * @constant
             */
            networkEgress: "allowlist";
            /** Honeytokens */
            honeytokens?: string[];
        };
        /** ScannerResult */
        ScannerResult: {
            /** Id */
            id: string;
            /** Scanner */
            scanner: string;
            status: components["schemas"]["ScannerStatus"];
            severity?: components["schemas"]["Severity"] | null;
            /** Summary */
            summary: string;
            /** Evidence */
            evidence?: string[];
        };
        /**
         * ScannerStatus
         * @enum {string}
         */
        ScannerStatus: "passed" | "flagged" | "skipped";
        /** Scenario */
        Scenario: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            category: components["schemas"]["ScenarioCategory"];
            /** Setupfixture */
            setupFixture: string;
            /** Attackgoal */
            attackGoal: string;
            /** Successcriteria */
            successCriteria: string;
            /** Expecteddefense */
            expectedDefense: string;
            defaultSeverity: components["schemas"]["Severity"];
        };
        /**
         * ScenarioCategory
         * @enum {string}
         */
        ScenarioCategory: "prompt_injection" | "rag_injection" | "secret_exfiltration" | "tool_misuse" | "unsafe_browsing" | "policy_bypass";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /** TargetAgentRuntime */
        TargetAgentRuntime: {
            /**
             * Kind
             * @default mock_http
             * @constant
             */
            kind: "mock_http";
            /** Endpoint */
            endpoint: string;
            /** Agentkey */
            agentKey: string;
        };
        /** TargetAgentTemplate */
        TargetAgentTemplate: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Category */
            category: string;
            /** Recommendedscenarioids */
            recommendedScenarioIds: string[];
            agentSpec: components["schemas"]["AgentSpec"];
            runtime: components["schemas"]["TargetAgentRuntime"];
        };
        /** ToolRoute */
        ToolRoute: {
            /** Requestedtools */
            requestedTools: string[];
            /** Observedtools */
            observedTools: string[];
            /** Violations */
            violations: string[];
            /**
             * Rawstepcount
             * @default 0
             */
            rawStepCount: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfig"][];
                };
            };
        };
    };
    list_scenarios_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"][];
                };
            };
        };
    };
    list_target_agents_v1_target_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetAgentTemplate"][];
                };
            };
        };
    };
    list_repositories_v1_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryRecord"][];
                };
            };
        };
    };
    import_github_agent_v1_github_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubImportSource"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentImportRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_target_agent_v1_target_agents__target_agent_id__register_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_agent_project_endpoint_v1_agent_projects_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_agent_project_endpoint_v1_agent_projects_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProjectImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_token_v1_runs__run_id__events_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_fix_v1_runs__run_id__approve_fix_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveFixRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveFixResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_run_pr_v1_runs__run_id__request_pr_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPrResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_run_pr_v1_runs__run_id__approve_pr_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveFixRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPrResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_diff_v1_diffs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_diff_pr_v1_diffs__diff_id__request_pr_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPrResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    managed_agent_tool_routing_smoke_v1_managed_agent_tool_routing_smoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
